### ISSUE TITLE
Can this library be added to ClickHouse docs?

### ISSUE THREAD

**Issue by ruslandoga** [livebook-dev/req_ch#8]
👋 

I wonder if it would make sense to add ReqCH to https://clickhouse.com/docs/en/interfaces/third-party/client-libraries#elixir? I don't know how many people visit those pages, but for those who do it might be useful to know all the options.

**Comment by josevalim** [comment]
Please do!

**Comment by ruslandoga** [comment]
https://github.com/ClickHouse/ClickHouse/pull/73590
